### ISSUE TITLE
Import accounts without passwords

### ISSUE THREAD

**Issue by badjava** [future-tense/stargazer#30]
I didn't password protect my account when I exported it but now when I try to import it, the "import account" button is disabled until I enter at least 1 character in the Account Password field. How do you import an account with no password? By default, accounts are not password protected so unless you enabled this option in the account settings, any accounts created without a password cannot be imported as far as I can see.

**Comment by kfiresmith** [comment]
Hi @badjava  - I can't reproduce this in 1.5.3 on Linux - can you please try again, and maybe capture some screenshots if you are still seeing this?
