### ISSUE TITLE
wallet not saving contacts  1.5.3 on win x64 laptop 

### ISSUE THREAD

**Issue by woodycockburn** [future-tense/stargazer#31]
hi, wallet has received 29k xlm thru address, however I found that it will not save contacts, or allow a pasted address in send ? I hesitate to enter an address manually.  I have extracted the secret key from the QR code.
how should I proceed ? 
thanks
woody

**Comment by kfiresmith** [comment]
Hello @woodycockburn - are you still having problems?  If so, would you mind pinging this issue back to let me know?  I can run some tests on Windows to try to reproduce but I very much prefer not to have to if you are not still having problems.
