### ISSUE TITLE
Stargazer wallet won't send lumens

### ISSUE THREAD

**Issue by droppedin2life** [future-tense/stargazer#40]
I have had no problem sending lumens to my desktop star gazer wallet. Today I tried to send some lumens to Bittrex and nothing happened. I entered my bittrex wallet address, and the memo, and the amount I wanted to send, 20 XLM.  When I click on the send button, nothing happens. When I click on overview, the balance is the same. I have tried sending 100, and I have the same problem. I am running the latest version of Mac OSX High Sierra, and I have set my DNS to 8.8.8.8. How do I get my coins out of this wallet?

**Comment by Fonbaron11** [comment]
Hello, did you figure out how to solve the problem?

**Comment by kfiresmith** [comment]
Are you still having this problem @droppedin2life ?

**Comment by Fonbaron11** [comment]
i do

**Comment by kfiresmith** [comment]
Hi @Fonbaron11  - any chance you could attach some screenshots and additional information about which version of Stargazer you are running and on what platform?  Thanks!

**Comment by Fonbaron11** [comment]
hello 1.5.3 ios
Johan knows about my issue. If you are in contact with him, he will tell you all details

**Comment by kfiresmith** [comment]
Cool thanks @Fonbaron11  - I'll leave the ticket open, remove the 'needinfo' tag, and leave it be.  I don't have IOS to test on anyhow :(

**Comment by Fonbaron11** [comment]
can you please contact him and ask when he can continue on helping me in our Telegram chat?

**Comment by seanPhill** [comment]
It seems this issue has been unsolved for well over a year!
I am able to remove password protection from the Stargazer wallet by using the password, and the lock icon indicates it is unlocked, but I cannot save a Contact address (even though I evidently added some in early 2018) and I cannot send a transaction. 

I am getting "No payment options found" (when specifying 10000 XLM) I was getting no response at all with a larger amount, and when I put in just 21 XLM I got a [Send] button, but what good is that, when I need to send a large amount?

If there is a problem with a server, I cannot find any diagnostic information in the Stargazer wallet or logs that might even identify the particular server being used, or any error messages. 

(I got this error yesterday with version 1.6 and I upgraded to 1.7 and the problem continues. Still trying today.)

Every time I retry I have to enter the address and memo over again, as the Address Book will not save the Contact address.

**Comment by seanPhill** [comment]
Should I try using TEXT as the Memo type instead of ID??
Is that a safe idea? (No idea if it will work, but I am wondering whether it is sending with a Memo that is the problem.

Just checked. When filling in the address details in the Send page, part 1, it only allows an ID Memo Type.

**Comment by johansten** [comment]
@seanPhill 

It's not the memos, it's the path finding. SDF broke it.

**Comment by Fonbaron11** [comment]
i have the same problem wit 203k for three years already


пн, 20 июл. 2020 г. в 17:00, enAct eServices <notifications@github.com>:

**Comment by perryeth** [comment]
Has anybody got an idea about how to get my XRP coins out of stargazer.

**Comment by Fonbaron11** [comment]
u need to find Johan Sten


пн, 10 янв. 2022 г. в 02:03, perryeth ***@***.***>:
