### ISSUE TITLE
Security issue : "Export account" doesn't ask for the password

### ISSUE THREAD

**Issue by AudioScientist** [future-tense/stargazer#65]
If I understood well, "Export account" shows you the QR-Code of the private key of the account. But, even though the account is protected with a password (indeed, I cannot send XLM without my password), the password is not needed for exporting my private key!

Seems a major security issue to me :/

Precision:
- In my case, the account has been imported from an account generated with the [stellar.org account viewer](https://www.stellar.org/account-viewer/#!/).
- Stargazer 1.5.3 on Windows 10 64 bits.

**Comment by johansten** [comment]
The private key is encrypted, and you will have to enter the correct password on *import*

**Comment by AudioScientist** [comment]
Indeed, I hadn't checked the content of the QR-Code after setting the password, my bad :)
So, the QR-Code generated with the "Export account" can only be used with Stargazer? Or is it a standard encryption that I can use with other Stellar wallets/interfaces?

**Comment by johansten** [comment]
Only Stargazer for now. If you want to export the account somewhere else, you have to remove the password protection first, then copy the secret key.
