### ISSUE TITLE
Import account from a QR-code does not work

### ISSUE THREAD

**Issue by micressor** [future-tense/stargazer#81]
On Android with Stargazer 1.6.0 I get a white screen that won't recover.
I have to kill the app.

**Steps to reproduce:**
1. Settings > Apps > Stargazer: Kill app and delete data
2. Start Stargazer on android and try to import a QR-backup export of Stargazer (AppImage) on Linux.

**Comment by zorroxans** [comment]
Hi there, the app still does not work for version 1.6.0. I also get a white screen that won't recover.
Also, in Windows 10 the program does not work and in IOs. 
Hope you can fix this issue as I liked the app and did not have problems at the beginning. TKs!

**Comment by GutteApps** [comment]
Having the same issue on OSX, scanning QR code just leads to white screen. 
<img width="793" alt="screen shot 2018-08-19 at 23 33 34" src="https://user-images.githubusercontent.com/4751301/44312925-68381680-a408-11e8-9ad9-f87d93e17c04.png">

**Comment by GutteApps** [comment]
Downgrading to 1.5.3 worked for me.
