### ISSUE TITLE
Scanning QR codes still does not work on Android, Windows 10 and iOS.

### ISSUE THREAD

**Issue by zorroxans** [future-tense/stargazer#83]
Hi there, the app still does not work for version 1.6.0. I also get a white screen that won't recover.
Also, in Windows 10 the program does not work and in IOs.
Hope you can fix this issue as I liked the app and did not have problems at the beginning. Tks!

**Comment by GutteApps** [comment]
Same on OSX. People should beware of this wallet.

**Comment by GutteApps** [comment]
Downgrading to 1.5.3 worked for me.
