### ISSUE TITLE
macOS High Sierra 10.13.6 - TypeError: angular.module(...).info is not a function

### ISSUE THREAD

**Issue by John3-16** [future-tense/stargazer#86]
Ran the baseline steps no issue
Ran the Building for Desktop steps all work fine

- The last step is npm run start

The app opens up but is completely blank and unusable. See attachment.
![stargazer_2018-07-20_19-53](https://user-images.githubusercontent.com/18647491/43029760-3b520efa-8c57-11e8-9434-c3b93a7953d4.jpg)

**Comment by johansten** [comment]
Can you still open the menu, and activate the developer tools?

**Comment by armanfranco** [comment]
I've got the same issue. Developer tools does open.
When installing in electron, these warnings show up:

npm WARN electron-builder-squirrel-windows@20.24.2 requires a peer of app-builder-lib@~20.24.2 but none is installed. You must install peer dependencies yourself.
npm WARN Stargazer@1.6.0 No repository field.

**Comment by johansten** [comment]
I just went through it myself, since I had to reinstall my computer anyway.

in `electron/package.json`, with these settings, everything works for me on 10.13.6.

  "devDependencies": {
    "ajv": "^6.5.2",
    "electron": "^2.0.5",
    "electron-builder": "^20.24.4",
    "electron-builder-squirrel-windows": "^20.24.2"
  },

**Comment by pavelku** [comment]
Same here. I have os x 10.13.4. Changing electron/package.json as per the previous-post instructions. The WARN disappeared but the app is still blank. Menu is accessible and dev tools can be turned on.

**Comment by pavelku** [comment]
yup, it is crying :)
![image](https://user-images.githubusercontent.com/444352/43102592-d6360b6c-8ecb-11e8-856e-dd5b5cea2623.png)

**Comment by pavelku** [comment]
Btw. that was after pulling the code again. Before the npm install for the baseline app finished clean. Now I get this:
![image](https://user-images.githubusercontent.com/444352/43102730-34ec754c-8ecc-11e8-8ea7-b40d92cafaa4.png)
I don't recall getting any error before the last pull.

**Comment by johansten** [comment]
Not exactly sure how I got past that, but that's an error in node-gyp. Will look into it.

It *might* be enough to
```
cd /usr/local/lib/node_modules/npm/
npm update node-gyp
```

**Comment by ianGre** [comment]
I had the same problem with the previous wallet version (on High Sierra) and am downloading 1.6.0, hoping it would fix the problem. I might try your idea above, if it happens in a minute.

**Comment by John3-16** [comment]
Hey pavelku after setting up Visual Code to debug it I got the same error that you did.

**Comment by John3-16** [comment]
I re-downloaded the zip file, re-walked the setup steps.  Everything went smoothly. Then run it and right back to the blank screen.  Developer menu works.  Here is the error

    Failed to load resource: net::ERR_FILE_NOT_FOUND
    stargazer.js:sourcemap:112971 Uncaught TypeError: angular.module(...).info is not a function
        at stargazer.js:sourcemap:112971
        at Object.defineProperty.value (stargazer.js:sourcemap:114173)
        at __webpack_require__ (stargazer.js:sourcemap:20)
        at Object.<anonymous> (stargazer.js:sourcemap:112906)
        at __webpack_require__ (stargazer.js:sourcemap:20)
        at Object.<anonymous> (stargazer.js:sourcemap:112836)
        at __webpack_require__ (stargazer.js:sourcemap:20)
        at stargazer.js:sourcemap:63
        at stargazer.js:sourcemap:66
    stargazer.js:sourcemap:19788 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
    Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
    http://errors.angularjs.org/1.5.3/$injector/nomod?p0=app
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:15309:12
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:17275:17
        at ensure (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:17199:38)
        at module (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:17273:14)
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19765:22
        at forEach (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:15562:20)
        at loadModules (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19749:5)
        at createInjector (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19671:19)
        at doBootstrap (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16951:20)
        at bootstrap (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16972:12)
    http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'app'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.3%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A15309%3A12%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A17275%3A17%0A%20%20%20%20at%20ensure%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A17199%3A38)%0A%20%20%20%20at%20module%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A17273%3A14)%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A19765%3A22%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A15562%3A20)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A19749%3A5)%0A%20%20%20%20at%20createInjector%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A19671%3A19)%0A%20%20%20%20at%20doBootstrap%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A16951%3A20)%0A%20%20%20%20at%20bootstrap%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A16972%3A12)
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:15309:12
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:17275:17
        at ensure (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:17199:38)
        at module (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:17273:14)
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19765:22
        at forEach (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:15562:20)
        at loadModules (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19749:5)
        at createInjector (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19671:19)
        at doBootstrap (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16951:20)
        at bootstrap (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16972:12)
    http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'app'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.3%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A15309%3A12%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A17275%3A17%0A%20%20%20%20at%20ensure%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A17199%3A38)%0A%20%20%20%20at%20module%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A17273%3A14)%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A19765%3A22%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A15562%3A20)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A19749%3A5)%0A%20%20%20%20at%20createInjector%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A19671%3A19)%0A%20%20%20%20at%20doBootstrap%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A16951%3A20)%0A%20%20%20%20at%20bootstrap%20(file%3A%2F%2F%2FUsers%2Fgumpy%2FWallets%2Fstargazer-master%2Felectron%2Fapp%2Fjs%2Fstargazer.js%3A16972%3A12)
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:15309:12
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19788:15
        at forEach (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:15562:20)
        at loadModules (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19749:5)
        at createInjector (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:19671:19)
        at doBootstrap (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16951:20)
        at bootstrap (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16972:12)
        at angularInit (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:16857:5)
        at file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:45950:5
        at HTMLDocument.trigger (file:///Users/gumpy/Wallets/stargazer-master/electron/app/js/stargazer.js:18368:7)
    /Users/gumpy/Wallets/stargazer-master/electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js:188 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks.

    For more information and help, consult https://electronjs.org/docs/tutorial/security.
    This warning will not show up once the app is packaged.

**Comment by pavelku** [comment]
Same here. After running npm update node-gyp the crash while building disappeared but the blank screen is still there.
