### ISSUE TITLE
Federated address should be validated against <,*>

### ISSUE THREAD

**Issue by fnando** [future-tense/stargazer#90]
If I try to use `user+multiple words*domain.com`, Stargazer rejects the address. Using URI encoded value works just fine (e.g. `user+multiple%20words%20*domain.com`). As per [documentation](https://www.stellar.org/developers/guides/concepts/federation.html):

> The domain can be any valid RFC 1035 domain name. The username is limited to printable UTF-8 with whitespace and the following characters excluded: `<*,>` Although of course the domain administrator can place additional restrictions on usernames of its domain.

According to ^^^, wallets shouldn't reject anything other than `<*,>`, as it's up to the domain administrator to decide which characters should be valid (I'm not rejecting whitespaces on mine).

**Comment by johansten** [comment]
> The username is limited to printable UTF-8 **with whitespace and the following characters excluded**: <*,>

That's how I read it, and IIRC that's how they've been specified previously.
