### ISSUE TITLE
Can't sign transactions

### ISSUE THREAD

**Issue by fx0ne** [future-tense/stargazer#93]
Looks like Stargazer can't be used to send out lumens or any asset any longer. Any account created no longer has a signer. Strange.

**Comment by johansten** [comment]
SDF published a breaking change in Horizon v0.17, that removed a (deprecared) field in the API response.

I'll get an update out, but have to decide whether to do a hot-fix *just* for this, or to include some other unreleased updated.

**Comment by tallerwild** [comment]
Would it fix the ability to send XLM from Stargazer?

**Comment by johansten** [comment]
Yes.

There has been a bunch of other changes in SDKs and server responses, but I'll get a new version out before Monday.

**Comment by rattonnmgn** [comment]
Hoping to get a fix soon :) 
Anyway, good luck with the coding!

**Comment by tallerwild** [comment]
Hey @johansten 

May I wonder if we should expect the fix by the end of the week? :)

**Comment by johansten** [comment]
@rattonnmgn, @tallerwild 
The 1.7.0 fixes this, if you're on desktop just go here, https://github.com/future-tense/stargazer/releases, and get the latest.

For Android, I'm working on uploading it right now.

**Comment by rattonnmgn** [comment]
Great, works perfectly again. Thanks!
